apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx.fullname" . }}-ocr-default
  labels:
  {{- include "nginx.labels" . | nindent 4 }}
  annotations:
    serviceAccount: ocr-default@{{ .Values.project_id }}.iam.gserviceaccount.com