kind: Namespace
apiVersion: v1
metadata:
  name: nginx
  labels:
    name: nginx

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: ocr-default@pasvel-moj-d-ocr.iam.gserviceaccount.com
  name: ocr-default
  namespace: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccount: ocr-default
      containers:
      - name: nginx
        image: me-west1-docker.pkg.dev/pasvel-moj-d-ocr/ocr-d-docker/test:latest
        # image: nginx:1.27.0-alpine-slim
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.3.104.200
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
