kind: Namespace
apiVersion: v1
metadata:
  name: nginx-test
  labels:
    name: nginx-test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: ocr-default@pasvel-moj-t-ocr.iam.gserviceaccount.com
  name: ocr-default
  namespace: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      serviceAccount: ocr-default
      containers:
      - name: nginx-test
        image: me-west1-docker.pkg.dev/pasvel-moj-t-ocr/ocr-t-docker/pasvel:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: nginx
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.4.104.200
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-test
