kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: ocr-default@pasvel-moj-d-ocr.iam.gserviceaccount.com
  name: ocr-default
  namespace: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccount: ocr-default
      containers:
      - name: test
        image: me-west1-docker.pkg.dev/pasvel-moj-d-ocr/ocr-d-docker/test:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.3.104.200
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: test
