kubernetesClusterDomain: cluster.local
project_id: pasvel-moj-d-ocr
namespace: pasvel
image: me-west1-docker.pkg.dev/pasvel-moj-d-ocr/ocr-d-docker/pasvel:latest
replicas: 1
type: LoadBalancer
ports:
  - port: 80
    protocol: TCP
    targetPort: 80
