apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocr-default
  namespace: nginx
  labels:
  {{- include "helm-nginx.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ocrDefault.serviceAccount.annotations | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
  {{- include "helm-nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
    {{- include "helm-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: nginx
      {{- include "helm-nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.nginx.nginx.image.repository }}:{{ .Values.nginx.nginx.image.tag
          | default .Chart.AppVersion }}
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
      serviceAccount: ocr-default
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
  {{- include "helm-nginx.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: {{ .Values.nginx.type }}
  selector:
    app: nginx
  {{- include "helm-nginx.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.nginx.ports | toYaml | nindent 2 }}